#SignRent configuration!
plugin:
   datasource: database
#The file where plugin data is stored into
   db:
      database: signdb
      table:
         name: signdb
         columns:
            name: player
            location: location
            duration: duration
            price: price
            rented: rented
            expire: expire
      

sign:
#The tag used to start signs
   tag: '||SR||'
#The min price allowed for a sign
   minprice: 10
#The max price allowed for a sign
   maxprice: 10000
#The min amount of days a sign can be set to
   mindays: 1
#The max amount of days a sign can be set to
   maxdays: 30
#The max late in paying the sign before losing property
   maxlate: 7
#How many days must be left to be able to renew
   renewdays: 7
   line:
      available:
         - SignRent
         - Disponibile
         - $d Giorni
         - $p
      rented:
         - SignRent
         - $n
         - $e giorni
         - $p/$d
      late:
         - SignRent
         - $n
         - $e giorni!
         - $p/$d
tools:
   rent:
#the ID of the tool used to rent a sign
      id: 280
#the name that appears in chat
      name: Stick
   renew: 
#the ID of the tool used to rent a sign
      id: 318
#the name that appears in chat
      name: Flint