name: SignRent
main: com.github.FrancescoDeSa.SignRent
version: 0.4
depend: [Vault]
description: This plugin allows the creation of rental signs
author: FrancescoDeSa (francesco.desantis.1803@gmail.com)
database: false

permissions:
   signrent.*:
      description: Accesso ad ogni comando
      children:
         signrent.sign.place: true
         signrent.sign.remove: true
         signrent.sign.use: true

   signrent.sign.place:
      description: Permesso di piazzare un cartello
      default: false

   signrent.sign.remove:
      description: Permesso di eliminare i cartelli
      default: false

   signrent.sign.use:
      description: Permesso di usare i cartelli
      default: true